const QUESTION = [
    // --- HTML - Beginner ---
    { category: "HTML", difficulty: "beginner", question: "Which tag is used to create a hyperlink?", options: ["<link>", "<a>", "<href>", "<url>"], answer: 1 },
    { category: "HTML", difficulty: "beginner", question: "Which tag defines the largest heading?", options: ["<h6>", "<heading>", "<h1>", "<head>"], answer: 2 }, 
    { category: "HTML", difficulty: "beginner", question: "What does HTML stand for?", options: ["Hyper Trainer Marking Language", "HyperText Markup Language", "HyperText Markdown Language", "Home Tool Markup Language"], answer: 1 },
    { category: "HTML", difficulty: "beginner", question: "Which attribute specifies an image's alternate text?", options: ["title", "alt", "src", "description"], answer: 1 },
    { category: "HTML", difficulty: "beginner", question: "Which tag is used for an unordered list?", options: ["<ol>", "<list>", "<ul>", "<li>"], answer: 2},
    { category: "HTLM", difficulty: "beginner", question: "Which tag creates a line break?", options: ["<break>", "<lb>", "<br>", "<newline>"], answer: 2 },
    { category: "HTLM", difficulty: "beginner", question: "What is the correct HTML for inserting an image?", options: ["<img src='x.jpg>", "<image src='x.jpg'>", "<picture>x.jpg</picture>", "<img>x.jpg</img>"], answer: 0 },
    { category: "HTML", difficulfy: "beginner", question: "Which tag is used to define a table row?", options: ["<td>", "<tr>", "<row>", "<th>"], answer: 1 },
    { category: "HTML", difficulfy: "beginner", question: "Which doctype is correcy for HTML5?", options: ["<!DOCTYPE html5>", "<!DOCTYPE HTML PUBLIC>", "<!DOCTYPE html>", "<!HTML5>"], answer: 2 },
    { category: "HTML", difficulty: "beginner", question: "Which tag is used to add a comment in HTML?", options: ["// comment", "<!-- comment -->", "/* comment */", "# comment"], answer: 1 },

    //--- HTML - Advanced ---
    { category: "HTML", difficulty: "advanced", question: "Which attribute makes an input field required?", options: ["mandatory", "required", "validate", "need"], answer: 1 },
    { category: "HTML", difficulty: "advanced", question: "Which element is used for playing audio files?", options: ["<sound>", "<media>", "<audio>", "<play>"], answer: 2 },
    { category: "HTML", difficulty: "advanced", question: "What does the 'defer' attribute do on a script tag?", options: ["Deletes the script", "Runs script immediately", "Delays script execution until HTML is parsed", " Minifies the script" ], answer: 2 },
    { category: "HTML", difficulty: "advanced", question: "Which tag is semantically correct for a navigation menu?", options: ["<menu>", "<nav>", "<navigation>", "<links>"], answer: 1 },
    { category: "HTML", difficulty: "advanced", question: "What is the purpose of the 'date-*' attribute?", options: ["Styling elements", "Storing custom data on an element", "Linking external files", "Validating forms"], answer: 1 },
    { category: "HTML", difficulty: "advanced", question: "Which input type shows a date picker?", options: ["type='calendar'", "type='date'", "type='datetime'", "type='pick'"], answer: 1 },
    { category: "HTML", difficulty: "advanced", question: "What does the 'srcset' attribute on <img> do?", options: ["Sets a fallback image", "Provides multime image sizes for responsive loading", "Sets image source only", "Crops the image"], answer: 1 },
    { category: "HTML", difficulty: "advanced", question: "Which element groups related form controls?", options: ["<group>", "<fieldset>", "section>", "<formgroup>"], answer: 1 },
    { category: "HTML", difficulty: "advanced", question: "What is the semantic tag for independent, self-contained content?", options: ["<article>", "<section>", "<div>", "<content>"], answer: 0 },
    { category: "HTML", difficulty: "advanced", question: "Which attributeprevents a form field from being edited but still submits its value?", options: ["disabled", "readonly", "locked", "static"], answer: 1 },

    //--- CSS - Beginner ---
    { category: "CSS", difficulty: "beginner", question: "Which property changes text color?", options: ["font-color", "text-color", "color", "foreground"], answer: 2 },
    { category: "CSS", difficulty: "beginner", question: "Which symbol is used for a class selector?", options: ["#", ".", "*", "&"], answer: 1 },
    { category: "CSS", difficulty: "beginner", question: "Which property controls element spacing outide its border?", options: ["padding", "margin", "spacing", "gap"], answer: 1 },
    { category: "CSS", difficulty: "beginner", question: "Which property is used to change background color?", options: ["bgcolor", "background-color", "color-bg", "bg"], answer: 1 },
    { category: "CSS", difficulty: "beginner", question: "How do you make text bold in CSS?", options: ["font-weight: bold;", "text-style:bold;", "font: bold;", "weght: bold;"], answer: 0 },
    { category: "CSS", difficulty: "beginner", question: "which symbol targets an ID selector?", options: [".", "#", "@", "%"], answer: 1 },
    { category: "CSS", difficulty: "beginner", question: "Which property controls text size?", options: ["text-size", "font-size", "size", "text-style"], answer: 1 },
    { category: "CSS", difficulty: "beginner", question: "Which value centers a block element horizontally with margin?", options: ["margin: center;", "margin: 0 auto;", "align: center;", "center: true;"], answer: 1 },
    { category: "CSS", difficulty: "beginner", question: "Which property adds space inside an element's border?", options: ["margin", "padding", "border-space", "inset"], answer: 1 },
    { category: "CSS", difficulty: "beignner", question: "Which property hides an element competely(no space reserved)?", options: ["visibility: hidden;", "display: none;", "opacity: 0;", "hide: true;"], answer: 1 },

    { category: "CSS", difficulty: "advanced", question: "Which display value creates a flexible box layout?", options: ["display: block;", "display: flex;", "display: grid;", "display: inline;"], answer: 1 },
    { category: "CSS", difficulty: "advanced", question: "What does 'z-index' control?", options: ["Element width", "Stacking order along the Z axis", "Zoom level", "Font size scaling"], answer: 1 },
    { category: "CSS", difficulty: "advanced", question: "What pseudo-class targets the first child element?", options: ["first", "first-child", ":child(1)", ":top"], answer: 1 },
    { category: "CSS", difficulty: "abvanced", question: "What does 'position: sticky' do?", options: ["Always fixed to viewport", "Toggles between relative and fixed in scroll position", "Removes element from flow", "Same as absolute"], answer: 1 },
    { category: "CSS", difficulty: "advanced", question: "Which unit is relative to the root element's font size?", options: ["em", "rem", "vh", "%"], answer: 1 },
    { category: "CSS", difficulfy: "advanced", question: "Which property defines the gap between flex/grid items?", options: ["space-between", "gap", "margin-gap", "spacing"], answer: 1 },
    { category: "CSS", difficulty: "advanced", question: "What does 'box-sizing: border-box' do?", options: ["Removes borders", "Includes padding and border in element's total width/heigh", "Adds a box shadow", "Makes element a flex box"], answer: 1 },
    { category: "CSS", difficulty: "advanced", question: "which CSS feature lets you define reusable values?", options: ["CSS variables (custom properties)", "CSS imports", "CSS mixins", "CSS macros"], answer: 1 },
    { category: "CSS", difficulty: "advanced", question: "What does 'transform: translateY(-10px)' do?", options: ["Scales element vertically", "Moves element 10px up", "Rotates element", "Skews elment"], answer: 0 },
    { category: "CSS", difficulty: "advanced", question: "Which media query targets screens smaller than 600px?", options: ["@media (max-width: 600px)", "@media (min-width: 600px)", "@media screen(600px)", "@media (size: 600px)"], answer: 1 },

    //--- JavaScript - Beginner ---
    { category: "JavaScript", difficulty: "begginer", question: "Which keyword declares a that can be reassigned?", options: ["const", "let", "var only", "static"], answer: 1 },
    { category: "JavaScript", difficulty: "begginer", question: "Which symbol is used for strict equality?", options: ["=", "==", "===", "=>"], answer: 2 },
    { category: "JavaScript", difficulty: "begginer", question: "How do you write a comment in JavaScript?", options: ["<!-- comment -->", "// comment", "# comment", "** comment **"], answer: 1 },
    { category: "JavaScript", difficulty: "begginer", question: "Which method adds an item to the end of an array?", options: ["array.add()", "array,push()", "array,append()", "array,insert()"], answer: 1 },
    { category: "JavaScript", difficulty: "begginer", question: "What does 'typeof 5' return?", options: ["'number'", "'integer'", "'int'", ",float'"], answer: 0 },
    { category: "JavaScript", difficulty: "begginer", question: "Which function converts a string to an integer?", options: ["Integer()", "parseInt()", "toInt()", "Number.Int()"], answer: 1 },
    { category: "JavaScript", difficulty: "begginer", question: "How do you write an if statement in JavaScript?", options: ["if x== 5", "if (x == 5)", "if x = 5 then", "if (x = 5):"], answer: 1 },
    { category: "JavaScript", difficolty: "begginer", question: "Which operator is used for string concatenation?", options: ["&", "+", "-", "concat"], answer: 1 },
    { category: "JavaScript", difficulty: "begginer", question: "Which keyword declares a function?", options: ["func", "function", "def", "method"], answer: 1 },
    { category: "JavaScript", difficulty: "begginer", question: "What does 'console.log()' do?", optiond: ["Deletes a variable", Prints, "output to the browser cosole", "Creates an alert popup", "Logs the user out"], answer: 1 },

    //--- JavaScript - Advanced ---
    { category: "JavaScript", difficulty: "advanced", question: "What does the '...' (spread) operator do in an array?", options: ["Detetes array items", "Expands array element individually", "Sorts the array", "Reverses the array"], answer: 1 },
    { category: "JavaScript", difficulty: "advanced", question: "What will 'typeof null' return?", options: ["'null'", "'undefined'", "'object'", "boolean"], answer: 2 },
    { category: "JavaScript", difficulty: "advanced", question: "Which method creates a new array by transforming each element?", options: ["forEach()", "map()", "filter()", "reduce()"], answer: 1 },
    { category: "JavaScript", difficulty: "advanced", question: "What is a closure in JavaScript?", options: ["A loop that never ends", "A function that remembers variables from its outer scope", "A way to close the browser tab", "A type of array"], answer: 1 },
    { category: "JavaScript", difficulty: "advanced", question: "Which method is used to handle a resolved Promise?", options: [".then()", ".resolve()", ".finish", ".done()"], answer: 0 },
    { category: "JavaScript", difficulty: "advanced", question: "What does 'event.preventDefault()' do?", options: ["Stops the event from bybbling", "Stops the default browser action for that event", "Removes the event listener", "Pauses JavaScript execution"], answer: 1 },
    { category: "JavaScript", difficulty: "advanced", question: "Which array method reduces all elements to a single value?", options: ["reduce()", "map()", "flat()", "some()"], answer: 0 },
    { category: "JavaScript", difficulty: "advanced", question: "What does 'async/await' help you do?", options: ["Write synchronous-looking asynchronous code", "Make code run faster", "Create loops", "Declare variables"], answer: 0 },
    { category: "JavaScript", difficulty: "advanced", question: "What does the '?.' (optional chaining) operator do?", options: ["Throws an error if a property is missing", "Safely access nested properties without errors if undefined", "Compares two values", "Creates a ternary expression"], answer: 1 }, 
    { category: "JavaScript", difficulty: "advanced", question: "Which keyword creates a block-scoped constant?", options: ["let", "var", "const", "static"], answer: 2 },
]
